apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 30s
  sourceRef:
    kind: GitRepository
    name: podinfo
  path: ./kustomize/environments/local
  prune: true
#  healthChecks:
#    - kind: Deployment
#      name: podinfo
#      namespace: default
  timeout: 30s